[workspace]
members = ["compat_rs", "bsd-sys", "tmux_rs", "compat_derive"]
resolver = "2"

[profile.release]
debug = true
panic = "abort"

[workspace.dependencies]
compat_rs    = { path = "./compat_rs" }
libc         = { version = "0.2.169" }
libevent-sys = { version = "0.3.0" }
paste        = { version = "1.0.15"  }
quote        = { version = "1.0.38"  }
syn          = { version = "2.0.96"  }

[workspace.lints.rust]
non_camel_case_types   = "allow"
non_snake_case         = "allow"
non_upper_case_globals = "allow" # warning still shows in rust-analyzer. bug: <https://github.com/rust-lang/rust-analyzer/issues/15344>
private_interfaces     = "allow"
unused                 = "allow"

[workspace.lints.clippy]
collapsible_if        = "allow"
manual_range_contains = "allow"
missing_safety_doc    = "allow"
needless_return       = "allow"
new_without_default   = "allow"
zero_ptr              = "allow"
