[workspace]
members = ["compat_rs", "bsd-sys", "tmux_rs", "compat_derive", "event"]
resolver = "2"

[profile.dev]
debug = true
debug-assertions = true
overflow-checks = true
panic = "abort"

[profile.release]
debug = true
debug-assertions = true
overflow-checks = true
panic = "abort"

[workspace.dependencies]
bitflags     = { version = "2.6.0" }
bindgen      = { version = "0.71.0", default-features = false, features = ["runtime"] } # want to tie to what libevent-sys uses, but 0.64.0 doesn't work for rust 2024
compat_rs    = { path = "./compat_rs" }
libc         = { version = "0.2.169" }
event        = { path = "./event" }
paste        = { version = "1.0.15"  }
quote        = { version = "1.0.38"  }
syn          = { version = "2.0.96"  }

# # BUGS
#
# Warnings disabled in Cargo.toml still show in rust-analyzer
# and must be allowed separately.
# - <https://github.com/rust-lang/rust-analyzer/issues/16628>
# - <https://github.com/rust-lang/rust-analyzer/issues/15344>

[workspace.lints.rust]
non_camel_case_types   = "allow"
non_snake_case         = "allow"
non_upper_case_globals = "allow"
private_interfaces     = "allow"
unused                 = "allow"
unsafe_op_in_unsafe_fn = "allow"

# oddly enough having this causes rust-analyzer to break, because of cargo clippy breaking
# unexpected_cfgs        = { level = "warn", check-cfg = ['cfg(disabled)'] }

[workspace.lints.clippy]
collapsible_if        = "allow"
collapsible_else_if   = "allow"
manual_range_contains = "allow"
missing_safety_doc    = "allow"
needless_return       = "allow"
new_without_default   = "allow"
zero_ptr              = "allow"
