[package]
name = "alerts"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
compat_rs = { version = "0.1.0", path = "../compat_rs" }
libc = { workspace = true }
tmux_h = { version = "0.1.0", path = "../tmux_h" }
