[package]
name = "compat_rs"
version = "0.1.0"
edition = "2021"

[dependencies]
bsd-sys          = { path = "../bsd-sys" }
libc             = "0.2"
libevent-sys     = "=0.3.0"
log              = "0.4.22"

[lints.rust]
non_camel_case_types = "allow"
non_snake_case       = "allow"
unused               = "allow"
unsafe_block_in_unsafe_fn = "allow" # renable after port finished

[lints.clippy]
missing_safety_doc   = "allow"
needless_return      = "allow"
non_camel_case_types = "allow"
zero_ptr             = "allow"
