[package]
name = "tmux_rs"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["staticlib", "lib"]

[dependencies]
compat_rs = { path = "../compat_rs" }
libc = { workspace = true }
libevent-sys = { version = "0.3.0" }
paste = { version = "1.0.15" }

[features]
systemd = []
sixel = []
utempter = []
