# https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions
on:
  schedule:
    # Run every Sunday at 2 AM UTC
    - cron: '0 2 * * 0'
  workflow_dispatch: # Allow manual triggering
name: beta-clippy

jobs:
  clippy:
    runs-on: ubuntu-latest
    steps:
      - name: Install system dependencies (ubuntu)
        run: |
          sudo apt-get update
          sudo apt-get install -y libncurses-dev libevent-dev
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: beta
          components: clippy
      - run: cargo clippy -- -Dwarnings
